# Generated by Django 5.1.3 on 2024-11-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='worker_cards/')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.worker')),
            ],
        ),
    ]
